typography_spectrum: 0.6168448934331536
color:
  brandStrength: 0.6840533458162099
  lightness: 0.6184879841748625
  saturation: 0.46367837488651276
  rhythmicContrast: 0.1190468817949295
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
opengraph:
  image: null
layout_spectrum: 0.4401974971406162
author:
  name: Michael
  email: info@structuredwateraz.com
  url: 'http://structuredwateraz.com'
name: Structured Water AZ
navigation:
  - id: 'http://structuredwateraz.com'
    url: 'http://structuredwateraz.com'
    name: Store
    type: external
  - id: 'http://structuredwateraz.com/about'
    url: 'http://structuredwateraz.com/about'
    name: About
    type: external
title: Structure your water...Structure your breathing...Structure your life!
